# encoding: UTF-8
viewed = Group.find_by_name("viewed")
saved = Group.find_by_name("saved")
discussed = Group.find_by_name("discussed")
cited = Group.find_by_name("cited")
recommended = Group.find_by_name("recommended")
other = Group.find_by_name("other")

# Load sources
viewed = Group.find_by_name("viewed")
saved = Group.find_by_name("saved")
discussed = Group.find_by_name("discussed")
cited = Group.find_by_name("cited")
recommended = Group.find_by_name("recommended")
other = Group.find_by_name("other")

# These sources are installed and activated by default
citeulike = Citeulike.find_or_create_by_name(
	:name => "citeulike",
	:display_name => "CiteULike",
  :description => "CiteULike is a free social bookmarking service for scholarly content.",
	:state_event => "activate",
	:group_id => saved.id)
pubmed = PubMed.find_or_create_by_name(
  :name => "pubmed",
  :display_name => "PubMed",
  :description => "PubMed Central is a free full-text archive of biomedical literature at the National Library of Medicine.",
  :state_event => "activate",
  :group_id => cited.id)
wordpress = Wordpress.find_or_create_by_name(
  :name => "wordpress",
  :display_name => "Wordpress.com",
  :description => "Wordpress.com is one of the largest blog hosting platforms.",
  :state_event => "activate",
  :group_id => discussed.id)
reddit = Reddit.find_or_create_by_name(
  :name => "reddit",
  :display_name => "Reddit",
  :description => "User-generated news links.",
  :state_event => "activate",
  :group_id => discussed.id)
wikipedia = Wikipedia.find_or_create_by_name(
  :name => "wikipedia",
  :display_name => "Wikipedia",
  :description => "Wikipedia is a free encyclopedia that everyone can edit.",
  :state_event => "activate",
  :group_id => discussed.id)

# These sources are not installed by default
datacite = Datacite.find_or_create_by_name(
  :name => "datacite",
  :display_name => "DataCite",
  :description => "Helping you to find, access, and reuse research data.",
  :group_id => cited.id)
pmc_europe = PmcEurope.find_or_create_by_name(
  :name => "pmceurope",
  :display_name => "PMC Europe Citations",
  :description => "Europe PubMed Central (Europe PMC) is an archive of life sciences journal literature.",
  :group_id => cited.id)
pmc_europe_data = PmcEuropeData.find_or_create_by_name(
  :name => "pmceuropedata",
  :display_name => "PMC Europe Database Citations",
  :description => "Europe PubMed Central (Europe PMC) is an archive of life sciences journal literature.",
  :group_id => cited.id)
scienceseeker = ScienceSeeker.find_or_create_by_name(
  :name => "scienceseeker",
  :display_name => "ScienceSeeker",
  :description => "Research Blogging is a science blog aggregator.",
  :group_id => discussed.id)
nature = Nature.find_or_create_by_name(
  :name => "nature",
  :display_name => "Nature Blogs",
  :description => "Nature Blogs is a science blog aggregator.",
  :group_id => discussed.id)
openedition = Openedition.find_or_create_by_name(
  :name => "openedition",
  :display_name => "OpenEdition",
  :description => "OpenEdition is the umbrella portal for OpenEdition Books, Revues.org, Hypotheses and Calenda in the humanities and social sciences.",
  :group_id => discussed.id)
