#!/bin/bash
#
# $HeadURL$
# $Id$
#
# Copyright (c) 2009-2010 by Public Library of Science, a non-profit corporation
# http://www.plos.org/
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# workling    This shell script takes care of starting and stopping
#                    the workling handler daemon
# chkconfig: 345 99 99
# description: The workling handler daemon
# processname: workling
# pidfile: /opt/alm/current/tmp/workling.pid

# Source function library.
. /etc/rc.d/init.d/functions

# Source networking configuration.
[ -f /etc/sysconfig/network ] && . /etc/sysconfig/network

SCRIPT_PATH=/opt/alm/current/script/workling_client
RAILS_ENV=production

[ -f /etc/workling ] && . /etc/workling

if [ -d /opt/ree/current/bin ]; then
  # Use Ruby Enterprise Edition
  RUBY_DIR=/opt/ree/current/bin
  PATH=$RUBY_DIR:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
else
  # Use the machine's default 'ruby'
  RUBY_DIR=/usr/bin
fi

start() {
  echo -n $"Starting workling: "
  RAILS_ENV=$RAILS_ENV $RUBY_DIR/ruby $SCRIPT_PATH start
  [ $? -eq 0 ] && success "workling startup" || failure "workling startup"
  echo
}

stop() {
  echo -n $"Stopping workling: "
  RAILS_ENV=$RAILS_ENV $RUBY_DIR/ruby $SCRIPT_PATH stop
  [ $? -eq 0 ] && success "workling shutdown" || failure "workling shutdown"
  echo
}

case "$1" in
  start)
    start
  ;;
  stop)
    stop
  ;;
  restart)
    stop
    sleep 3
    start
  ;;
  *)
    echo $"Usage: $0 {start|stop|restart}"
    exit 1
esac
