#!/bin/bash
#
# workling    This shell script takes care of starting and stopping
#                    the workling handler daemon
# chkconfig: 345 99 99
# description: The workling handler daemon
# processname: workling
# pidfile: /opt/alm/current/tmp/workling.pid

# Source function library.
. /etc/rc.d/init.d/functions

# Source networking configuration.
[ -f /etc/sysconfig/network ] && . /etc/sysconfig/network

SCRIPT_PATH=/opt/alm/current/script/workling_client

if [ -d /opt/ree/current/bin ]; then
  # Use Ruby Enterprise Edition
  RUBY_DIR=/opt/ree/current/bin
  PATH=$RUBY_DIR:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
else
  # Use the machine's default 'ruby'
  RUBY_DIR=/usr/bin
fi

start() {
  echo -n $"Starting workling: "
  $RUBY_DIR/ruby $SCRIPT_PATH start
  [ $? -eq 0 ] && success "workling startup" || failure "workling startup"
  echo
}

stop() {
  echo -n $"Stopping workling: "
  $RUBY_DIR/ruby $SCRIPT_PATH stop
  [ $? -eq 0 ] && success "workling shutdown" || failure "workling shutdown"
  echo
}

case "$1" in
  start)
    start
  ;;
  stop)
    stop
  ;;
  restart)
    stop
    sleep 3
    start
  ;;
  *)
    echo $"Usage: $0 {start|stop|restart}"
    exit 1
esac
